---
  - type: .*user\.ApiUser\.ApiRole
    specAsParameter:
      - type: string
        enum:
          - "admin"
          - "user"
  - type: .*user\.ApiUser\.ApiStatus
    specAsParameter:
      - type: string
        enum:
          - "new"
          - "approved"
