---
  - type: .*user\.RoleFormat
    specAsParameter:
      - type: string
        enum:
          - "admin"
          - "user"
  - type: .*user\.StatusFormat
    specAsParameter:
      - type: string
        enum:
          - "new"
          - "approved"