---
  swagger: "2.0"
  info:
    title: "Bitworks assessment API"
    version: "1.0"
  consumes:
    - application/json
  produces:
    - application/json
  host: "sop-ci.z1.netpoint-dc.com:9000"
  basePath: "/api/v1.0"
  schemes:
    - "http"
  securityDefinitions:
    apiKey:
      type: apiKey
      name: X-Auth-Token
      description: JWT
      in: header
  security:
    - apiKey: []
  responses:
    'BadRequest':
      description: Bad Request
      schema:
        $ref: '#/definitions/controllers.api.Response.Error'
    'Unauthorized':
      description: Unauthorized
      schema:
        $ref: '#/definitions/controllers.api.Response.Error'
    'Forbidden':
      description: Forbidden
      schema:
        $ref: '#/definitions/controllers.api.Response.Error'
    'NotFound':
      description: Not Found
      schema:
        $ref: '#/definitions/controllers.api.Response.Error'
    'InternalServerError':
      description: Internal Server Error
      schema:
        $ref: '#/definitions/controllers.api.Response.Error'
    'Conflict':
      description: Conflict
      schema:
        $ref: '#/definitions/controllers.api.Response.Error'
  parameters:
    pageSize:
      name: size
      in: query
      type: integer
      description: Page size
    pageNumber:
      name: number
      in: query
      type: integer
      description: Page number
