---
  - type: .*user\.ApiUser\.ApiRole
    specAsParameter:
      - type: string
        enum:
          - "admin"
          - "user"
  - type: .*user\.ApiUser\.ApiStatus
    specAsParameter:
      - type: string
        enum:
          - "new"
          - "approved"
  - type: .*user\.ApiUser\.ApiGender
    specAsParameter:
      - type: string
        enum:
          - "male"
          - "female"
  - type: .*.ApiForm\.ElementKind
    specAsParameter:
      - type: string
        enum:
          - "radio"
          - "textfield"
          - "textarea"
          - "checkbox"
          - "checkboxgroup"
          - "radio"
          - "select"
  - type: .*.ApiProject\.RelationKind
    specAsParameter:
      - type: string
        enum:
          - "classic"
          - "survey"
  - type: .*.ApiEvent\.EventStatus
    specAsParameter:
      - type: string
        enum:
          - "notStarted"
          - "inProgress"
          - "completed"
  - type: .*.ApiEvent\.NotificationKind
    specAsParameter:
      - type: string
        enum:
          - "preBegin"
          - "begin"
          - "preEnd"
          - "end"
  - type: .*.ApiEvent\.NotificationRecipient
    specAsParameter:
      - type: string
        enum:
          - "respondent"
          - "auditor"
  - type: java\.sql\.Timestamp
    specAsParameter:
      - type: string
        format: date-time
