---
  - type: .*user\.ApiUser\.ApiRole
    specAsParameter:
      - type: string
        enum:
          - "admin"
          - "user"
  - type: .*user\.ApiUser\.ApiStatus
    specAsParameter:
      - type: string
        enum:
          - "new"
          - "approved"
  - type: .*user\.ApiUser\.ApiGender
    specAsParameter:
      - type: string
        enum:
          - "male"
          - "female"
  - type: .*.ApiForm\.ElementKind
    specAsParameter:
      - type: string
        enum:
          - "textbox"
          - "radio"
          - "textfield"
          - "textarea"
          - "checkbox"
          - "checkboxgroup"
          - "radio"
          - "select"
